functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Полная мультиязычность
  - Наличие кнопки сброса категории
  - При нажатии на логотип должна открываться главная страница
  - При смене языка указывать цену в рублях
  - При добавлении товара в корзину должна быть возможность указать необходимое количество товара
  - При оформлении заказа должна быть возможность связаться к покупателем
  - В каталоге товаров должен отображаться рейтинг товара
  - При оформлении заказа корзина должна очищаться
